import React from "react"
import poster from "../../images/blog6.jpg"

const BlogListBox = () => {
  return (
    <a href="#" className="featured-list-col">
      <div className="blog-img">
        <img src={poster} alt="" />
      </div>
      <div className="context-col">
        <p className="context">
          5 min read <span>Updates</span>
        </p>
        <h5>Examples of Copy Generated By Artificial Intelligence</h5>
      </div>
    </a>
  )
}

export default BlogListBox
